### ISSUE TITLE
Kriss items in personal storage

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#286]

**Comment by ordeh** [comment]
Not a bug

**Comment by YuryiDasevich** [comment]
**Description:**
1) Once personal storage is available for the user it is fully filled with Kris+0 items
![image](https://user-images.githubusercontent.com/45947708/152032860-d7a5b0d8-61d9-4cf6-a626-5040a659adb3.png)
2) The issue appears only for New characters
3) The high priority of the issue is due to big inconvenience for users


@ordeh please correct me if I'm wrong, but I don't know any cases that issue appeared for a personal store of a character that has cleared it.

**Comment by ordeh** [comment]
@YuryiDasevich 
I personally have not encountered this either, I received this information from users.
